name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-18.04]
        otp-version: [21.3.8.17-1]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Prepare the environment
      run: |
        deb=esl-erlang_${{ matrix.otp-version }}~ubuntu~bionic_amd64.deb
        wget https://packages.erlang-solutions.com/erlang/debian/pool/${deb}
        sudo apt-get install --allow-downgrades --no-install-recommends ./${deb}
        sudo apt-get install --no-install-recommends pwgen wget docker docker-compose
        wget https://github.com/erlang/rebar3/releases/download/3.14.0/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/rebar3
        sudo systemctl start docker
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: sudo make all
